/*
 Copyright (C) 2016 Alexander Borisov
 
 This library is free software; you can redistribute it and/or
 modify it under the terms of the GNU Lesser General Public
 License as published by the Free Software Foundation; either
 version 2.1 of the License, or (at your option) any later version.
 
 This library is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 Lesser General Public License for more details.
 
 You should have received a copy of the GNU Lesser General Public
 License along with this library; if not, write to the Free Software
 Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 
 Author: lex.borisov@gmail.com (Alexander Borisov)
*/

#include "mycss/selectors/state.h"

bool mycss_selectors_state_token_all(mycss_entry_t* entry, mycss_token_t* token)
{
    return ((mycss_selectors_state_f)entry->parser_state)(entry, entry->selectors, entry->stylesheet->sel_list_last->selector, token);
}

bool mycss_selectors_state_token_skip_whitespace(mycss_entry_t* entry, mycss_token_t* token)
{
    if(token->type != MyCSS_TOKEN_TYPE_WHITESPACE) {
        return ((mycss_selectors_state_f)entry->parser_state)(entry, entry->selectors, entry->stylesheet->sel_list_last->selector, token);
    }
    
    return true;
}

void mycss_selectors_state_end(mycss_entry_t* entry)
{
    mycss_selectors_t* selectors = entry->selectors;
    mycss_selectors_entry_t* selector = entry->stylesheet->sel_list_last->selector;
    
    if(selector == NULL)
        return;
    
    if(selector->type == MyCSS_SELECTORS_TYPE_ATTRIBUTE ||
       selector->type == MyCSS_SELECTORS_TYPE_PSEUDO_CLASS_FUNCTION ||
       (selector->key == NULL && selector->value == NULL))
    {
        mycss_selectors_entry_clean(selector);
    }
    else {
        mycss_selectors_parser_selector_end(entry, selectors, selector, NULL);
    }
}

/* for unknown functions */
bool mycss_selectors_state_function_skip_all(mycss_entry_t* entry, mycss_selectors_t* selectors, mycss_selectors_entry_t* selector, mycss_token_t* token)
{
    if(token->type == MyCSS_TOKEN_TYPE_RIGHT_PARENTHESIS)
        return entry->parser_switch(entry, token);
    
    return true;
}

/* Generated by utils/selectors.pl and my hands edit (HAND_EDIT_BEGIN and HAND_EDIT_END) */

/* <combinator> */
bool mycss_selectors_state_combinator(mycss_entry_t* entry, mycss_selectors_t* selectors, mycss_selectors_entry_t* selector, mycss_token_t* token)
{
    switch (token->type) {
        case MyCSS_TOKEN_TYPE_COLUMN: {
            mycss_selectors_parser_selector_combinator_column(entry, selectors, selector, token);
            MyCSS_DEBUG_MESSAGE("mycss_selectors_state_combinator_column")
            entry->parser = entry->parser_switch;
            break;
        }
        case MyCSS_TOKEN_TYPE_DELIM: {
            if(*token->data == '+') {
                mycss_selectors_parser_selector_combinator_plus(entry, selectors, selector, token);
                MyCSS_DEBUG_MESSAGE("mycss_selectors_state_combinator_plus")
                entry->parser = entry->parser_switch;
            }
            else if(*token->data == '>') {
                mycss_selectors_parser_selector_combinator_greater_than(entry, selectors, selector, token);
                MyCSS_DEBUG_MESSAGE("mycss_selectors_state_combinator_greater_than")
                entry->parser_state = mycss_selectors_state_combinator_greater_than;
                
                if(entry->parser != mycss_selectors_state_token_skip_whitespace)
                    entry->parser = mycss_selectors_state_token_skip_whitespace;
            }
            else if(*token->data == '~') {
                mycss_selectors_parser_selector_combinator_tilde(entry, selectors, selector, token);
                MyCSS_DEBUG_MESSAGE("mycss_selectors_state_combinator_tilde")
                entry->parser = entry->parser_switch;
            }
            else {
                mycss_selectors_parser_expectations_error(entry, selectors, selector, token);
                entry->parser = entry->parser_switch;
                return false;
            }
            break;
        }
        default: {
            mycss_selectors_parser_expectations_error(entry, selectors, selector, token);
            entry->parser = entry->parser_switch;
            return false;
        }
    }
    
    return true;
}

bool mycss_selectors_state_combinator_greater_than(mycss_entry_t* entry, mycss_selectors_t* selectors, mycss_selectors_entry_t* selector, mycss_token_t* token)
{
    if(token->type == MyCSS_TOKEN_TYPE_DELIM) {
        if(*token->data == '>') {
            mycss_selectors_parser_selector_combinator_greater_than(entry, selectors, selector, token);
            MyCSS_DEBUG_MESSAGE("mycss_selectors_state_combinator_greater_than_greater_than")
            entry->parser = entry->parser_switch;
        }
        else {
            entry->parser = entry->parser_switch;
            return false;
        }
    }
    else {
        entry->parser = entry->parser_switch;
        return false;
    }
    
    return true;
}

/* <simple-selector> */
bool mycss_selectors_state_simple_selector(mycss_entry_t* entry, mycss_selectors_t* selectors, mycss_selectors_entry_t* selector, mycss_token_t* token)
{
    switch (token->type) {
        case MyCSS_TOKEN_TYPE_IDENT: {
            mycss_selectors_parser_selector_ident_type(entry, selectors, selector, token);
            MyCSS_DEBUG_MESSAGE("mycss_selectors_state_simple_selector_ident")
            
            entry->parser_state = mycss_selectors_state_simple_selector_ident;
            
            if(entry->parser != mycss_selectors_state_token_all)
                entry->parser = mycss_selectors_state_token_all;
            break;
        }
        case MyCSS_TOKEN_TYPE_DELIM: {
            // HAND_EDIT_BEGIN
            if(*token->data == '*') {
                mycss_selectors_parser_selector_ident_type(entry, selectors, selector, token);
                MyCSS_DEBUG_MESSAGE("mycss_selectors_state_simple_selector_asterisk")
                
                entry->parser_state = mycss_selectors_state_simple_selector_ident;
                
                if(entry->parser != mycss_selectors_state_token_all)
                    entry->parser = mycss_selectors_state_token_all;
            }
            // HAND_EDIT_END
            else if(*token->data == '.') {
                entry->parser_state = mycss_selectors_state_simple_selector_full_stop;
                
                if(entry->parser != mycss_selectors_state_token_all)
                    entry->parser = mycss_selectors_state_token_all;
            }
            else if(*token->data == '|') {
                // HAND_EDIT_BEGIN
                mycss_selectors_parser_selector_namespace_ident(entry, selectors, selector, token);
                // HAND_EDIT_END
                entry->parser_state = mycss_selectors_state_simple_selector_vertical_bar;
                
                if(entry->parser != mycss_selectors_state_token_all)
                    entry->parser = mycss_selectors_state_token_all;
            }
            else {
                entry->parser = entry->parser_switch;
                return false;
            }
            break;
        }
        case MyCSS_TOKEN_TYPE_COLON: {
            entry->parser_state = mycss_selectors_state_simple_selector_colon;
            
            if(entry->parser != mycss_selectors_state_token_all)
                entry->parser = mycss_selectors_state_token_all;
            break;
        }
        case MyCSS_TOKEN_TYPE_LEFT_SQUARE_BRACKET: {
            entry->parser_state = mycss_selectors_state_simple_selector_left_bracket;
            
            if(entry->parser != mycss_selectors_state_token_skip_whitespace)
                entry->parser = mycss_selectors_state_token_skip_whitespace;
            break;
        }
        case MyCSS_TOKEN_TYPE_HASH: {
            // HAND_EDIT_BEGIN
            //
            // need if some check after process mycss_selectors_state_simple_selector
            // if(entry->parser_state == mycss_selectors_state_simple_selector)
            //     printf("error");
            //
            entry->parser_state = NULL;
            // HAND_EDIT_END
            
            mycss_selectors_parser_selector_id(entry, selectors, selector, token);
            MyCSS_DEBUG_MESSAGE("mycss_selectors_state_simple_selector_hash")
            entry->parser = entry->parser_switch;
            break;
        }
        default: {
            entry->parser = entry->parser_switch;
            return false;
        }
    }
    
    return true;
}

bool mycss_selectors_state_simple_selector_left_bracket(mycss_entry_t* entry, mycss_selectors_t* selectors, mycss_selectors_entry_t* selector, mycss_token_t* token)
{
    if(token->type == MyCSS_TOKEN_TYPE_IDENT) {
        mycss_selectors_parser_selector_ident_attr(entry, selectors, selector, token);
        entry->parser_state = mycss_selectors_state_simple_selector_left_bracket_ident;
        
        if(entry->parser != mycss_selectors_state_token_all)
            entry->parser = mycss_selectors_state_token_all;
    }
    else if(token->type == MyCSS_TOKEN_TYPE_DELIM) {
        if(*token->data == '|') {
            // HAND_EDIT_BEGIN
            mycss_selectors_parser_selector_namespace_attr(entry, selectors, entry->stylesheet->sel_list_last->selector, token);
            // HAND_EDIT_END
            entry->parser_state = mycss_selectors_state_simple_selector_left_bracket_vertical_bar;
            
            if(entry->parser != mycss_selectors_state_token_all)
                entry->parser = mycss_selectors_state_token_all;
        }
        else {
            mycss_selectors_parser_expectations_error(entry, selectors, selector, token);
            entry->parser = entry->parser_switch;
            return false;
        }
    }
    else {
        mycss_selectors_parser_expectations_error(entry, selectors, selector, token);
        entry->parser = entry->parser_switch;
        return false;
    }
    
    return true;
}

bool mycss_selectors_state_simple_selector_left_bracket_vertical_bar(mycss_entry_t* entry, mycss_selectors_t* selectors, mycss_selectors_entry_t* selector, mycss_token_t* token)
{
    if(token->type == MyCSS_TOKEN_TYPE_IDENT) {
        mycss_selectors_parser_selector_after_namespace(entry, selectors, selector, token);
        entry->parser_state = mycss_selectors_state_shared_after_wq_name_attr;
        
        if(entry->parser != mycss_selectors_state_token_skip_whitespace)
            entry->parser = mycss_selectors_state_token_skip_whitespace;
    }
    else {
        mycss_selectors_parser_expectations_error(entry, selectors, selector, token);
        entry->parser = entry->parser_switch;
        return false;
    }
    
    return true;
}

bool mycss_selectors_state_simple_selector_left_bracket_ident(mycss_entry_t* entry, mycss_selectors_t* selectors, mycss_selectors_entry_t* selector, mycss_token_t* token)
{
    switch (token->type) {
        case MyCSS_TOKEN_TYPE_WHITESPACE: {
            entry->parser_state = mycss_selectors_state_shared_after_wq_name_attr;
            
            if(entry->parser != mycss_selectors_state_token_skip_whitespace)
                entry->parser = mycss_selectors_state_token_skip_whitespace;
            break;
        }
        case MyCSS_TOKEN_TYPE_INCLUDE_MATCH: {
            if(selector->value == NULL)
                selector->value = mycss_selectors_value_attribute_create(entry, true);
            
            mycss_selector_value_attribute(selector->value)->match = MyCSS_SELECTORS_MATCH_INCLUDE;
            entry->parser_state = mycss_selectors_state_shared_after_attr_matcher;
            
            if(entry->parser != mycss_selectors_state_token_skip_whitespace)
                entry->parser = mycss_selectors_state_token_skip_whitespace;
            break;
        }
        case MyCSS_TOKEN_TYPE_DASH_MATCH: {
            if(selector->value == NULL)
                selector->value = mycss_selectors_value_attribute_create(entry, true);
            
            mycss_selector_value_attribute(selector->value)->match = MyCSS_SELECTORS_MATCH_DASH;
            entry->parser_state = mycss_selectors_state_shared_after_attr_matcher;
            
            if(entry->parser != mycss_selectors_state_token_skip_whitespace)
                entry->parser = mycss_selectors_state_token_skip_whitespace;
            break;
        }
        case MyCSS_TOKEN_TYPE_PREFIX_MATCH: {
            if(selector->value == NULL)
                selector->value = mycss_selectors_value_attribute_create(entry, true);
            
            mycss_selector_value_attribute(selector->value)->match = MyCSS_SELECTORS_MATCH_PREFIX;
            entry->parser_state = mycss_selectors_state_shared_after_attr_matcher;
            
            if(entry->parser != mycss_selectors_state_token_skip_whitespace)
                entry->parser = mycss_selectors_state_token_skip_whitespace;
            break;
        }
        case MyCSS_TOKEN_TYPE_SUFFIX_MATCH: {
            if(selector->value == NULL)
                selector->value = mycss_selectors_value_attribute_create(entry, true);
            
            mycss_selector_value_attribute(selector->value)->match = MyCSS_SELECTORS_MATCH_SUFFIX;
            entry->parser_state = mycss_selectors_state_shared_after_attr_matcher;
            
            if(entry->parser != mycss_selectors_state_token_skip_whitespace)
                entry->parser = mycss_selectors_state_token_skip_whitespace;
            break;
        }
        case MyCSS_TOKEN_TYPE_SUBSTRING_MATCH: {
            if(selector->value == NULL)
                selector->value = mycss_selectors_value_attribute_create(entry, true);
            
            mycss_selector_value_attribute(selector->value)->match = MyCSS_SELECTORS_MATCH_SUBSTRING;
            entry->parser_state = mycss_selectors_state_shared_after_attr_matcher;
            
            if(entry->parser != mycss_selectors_state_token_skip_whitespace)
                entry->parser = mycss_selectors_state_token_skip_whitespace;
            break;
        }
        case MyCSS_TOKEN_TYPE_DELIM: {
            if(*token->data == '=') {
                if(selector->value == NULL)
                    selector->value = mycss_selectors_value_attribute_create(entry, true);
                
                mycss_selector_value_attribute(selector->value)->match = MyCSS_SELECTORS_MATCH_EQUAL;
                entry->parser_state = mycss_selectors_state_shared_after_attr_matcher;
                
                if(entry->parser != mycss_selectors_state_token_skip_whitespace)
                    entry->parser = mycss_selectors_state_token_skip_whitespace;
            }
            else if(*token->data == '|') {
                // HAND_EDIT_BEGIN
                mycss_selectors_parser_selector_namespace_attr(entry, selectors, selector, token);
                // HAND_EDIT_END
                entry->parser_state = mycss_selectors_state_simple_selector_left_bracket_ident_vertical_bar;
                
                if(entry->parser != mycss_selectors_state_token_all)
                    entry->parser = mycss_selectors_state_token_all;
            }
            else {
                mycss_selectors_parser_expectations_error(entry, selectors, selector, token);
                entry->parser = entry->parser_switch;
                return false;
            }
            break;
        }
        case MyCSS_TOKEN_TYPE_RIGHT_SQUARE_BRACKET: {
            mycss_selectors_parser_selector_end(entry, selectors, selector, token);
            MyCSS_DEBUG_MESSAGE("mycss_selectors_state_simple_selector_left_bracket_ident_right_bracket")
            entry->parser = entry->parser_switch;
            break;
        }
        default: {
            mycss_selectors_parser_expectations_error(entry, selectors, selector, token);
            entry->parser = entry->parser_switch;
            return false;
        }
    }
    
    return true;
}

bool mycss_selectors_state_simple_selector_left_bracket_ident_vertical_bar(mycss_entry_t* entry, mycss_selectors_t* selectors, mycss_selectors_entry_t* selector, mycss_token_t* token)
{
    if(token->type == MyCSS_TOKEN_TYPE_IDENT) {
        mycss_selectors_parser_selector_after_namespace(entry, selectors, selector, token);
        entry->parser_state = mycss_selectors_state_shared_after_wq_name_attr;
        
        if(entry->parser != mycss_selectors_state_token_skip_whitespace)
            entry->parser = mycss_selectors_state_token_skip_whitespace;
    }
    else {
        mycss_selectors_parser_expectations_error(entry, selectors, selector, token);
        entry->parser = entry->parser_switch;
        return false;
    }
    
    return true;
}

// HAND_EDIT_BEGIN
bool mycss_selectors_state_simple_selector_colon(mycss_entry_t* entry, mycss_selectors_t* selectors, mycss_selectors_entry_t* selector, mycss_token_t* token)
{
    switch (token->type) {
        case MyCSS_TOKEN_TYPE_IDENT: {
            mycss_selectors_parser_selector_pseudo_class(entry, selectors, selector, token);
            MyCSS_DEBUG_MESSAGE("mycss_selectors_state_simple_selector_colon_ident")
            entry->parser = entry->parser_switch;
            break;
        }
        case MyCSS_TOKEN_TYPE_COLON: {
            entry->parser_state = mycss_selectors_state_simple_selector_colon_colon;
            
            if(entry->parser != mycss_selectors_state_token_all)
                entry->parser = mycss_selectors_state_token_all;
            break;
        }
        case MyCSS_TOKEN_TYPE_FUNCTION: {
            mycss_selectors_parser_selector_pseudo_class_function(entry, selectors, selector, token);
            break;
        }
        default: {
            mycss_selectors_parser_expectations_error(entry, selectors, selector, token);
            entry->parser = entry->parser_switch;
            return false;
        }
    }
    
    return true;
}

bool mycss_selectors_state_simple_selector_colon_colon(mycss_entry_t* entry, mycss_selectors_t* selectors, mycss_selectors_entry_t* selector, mycss_token_t* token)
{
    if(token->type == MyCSS_TOKEN_TYPE_IDENT) {
        mycss_selectors_parser_selector_pseudo_element(entry, selectors, selector, token);
        MyCSS_DEBUG_MESSAGE("mycss_selectors_state_simple_selector_colon_colon_ident")
        entry->parser = entry->parser_switch;
    }
    else if(token->type == MyCSS_TOKEN_TYPE_FUNCTION) {
        mycss_selectors_parser_selector_pseudo_element_function(entry, selectors, selector, token);
    }
    else {
        mycss_selectors_parser_expectations_error(entry, selectors, selector, token);
        entry->parser = entry->parser_switch;
        return false;
    }
    
    return true;
}

bool mycss_selectors_state_simple_selector_colon_colon_function(mycss_entry_t* entry, mycss_selectors_t* selectors, mycss_selectors_entry_t* selector, mycss_token_t* token)
{
    if(token->type == MyCSS_TOKEN_TYPE_RIGHT_PARENTHESIS) {
        mycss_selectors_parser_selector_pseudo_element_function_end(entry, selectors, selector, token);
        MyCSS_DEBUG_MESSAGE("mycss_selectors_state_simple_selector_colon_colon_function_right_parenthesis")
        entry->parser = entry->parser_switch;
    }
    else {
        mycss_selectors_parser_expectations_error(entry, selectors, selector, token);
        entry->parser = entry->parser_switch;
        return false;
    }
    
    return true;
}

bool mycss_selectors_state_simple_selector_colon_function(mycss_entry_t* entry, mycss_selectors_t* selectors, mycss_selectors_entry_t* selector, mycss_token_t* token)
{
    if(token->type == MyCSS_TOKEN_TYPE_RIGHT_PARENTHESIS) {
        mycss_selectors_parser_selector_pseudo_class_function_end(entry, selectors, selector, token);
        MyCSS_DEBUG_MESSAGE("mycss_selectors_state_simple_selector_colon_function_right_parenthesis")
        entry->parser = entry->parser_switch;
    }
    else {
        mycss_selectors_parser_expectations_error(entry, selectors, selector, token);
        entry->parser = entry->parser_switch;
        return false;
    }
    
    return true;
}
// HAND_EDIT_END

bool mycss_selectors_state_simple_selector_full_stop(mycss_entry_t* entry, mycss_selectors_t* selectors, mycss_selectors_entry_t* selector, mycss_token_t* token)
{
    if(token->type == MyCSS_TOKEN_TYPE_IDENT) {
        mycss_selectors_parser_selector_class(entry, selectors, selector, token);
        MyCSS_DEBUG_MESSAGE("mycss_selectors_state_simple_selector_full_stop_ident")
        entry->parser = entry->parser_switch;
    }
    else {
        mycss_selectors_parser_expectations_error(entry, selectors, selector, token);
        entry->parser = entry->parser_switch;
        return false;
    }
    
    return true;
}

bool mycss_selectors_state_simple_selector_vertical_bar(mycss_entry_t* entry, mycss_selectors_t* selectors, mycss_selectors_entry_t* selector, mycss_token_t* token)
{
    if(token->type == MyCSS_TOKEN_TYPE_IDENT) {
        mycss_selectors_parser_selector_after_namespace(entry, selectors, selector, token);
        mycss_selectors_parser_selector_end(entry, selectors, selector, token);
        MyCSS_DEBUG_MESSAGE("mycss_selectors_state_simple_selector_vertical_bar_ident")
        entry->parser = entry->parser_switch;
    }
    else if(token->type == MyCSS_TOKEN_TYPE_DELIM) {
        if(*token->data == '*') {
            mycss_selectors_parser_selector_after_namespace(entry, selectors, selector, token);
            mycss_selectors_parser_selector_end(entry, selectors, selector, token);
            MyCSS_DEBUG_MESSAGE("mycss_selectors_state_simple_selector_vertical_bar_asterisk")
            entry->parser = entry->parser_switch;
        }
        else {
            mycss_selectors_parser_expectations_error(entry, selectors, selector, token);
            entry->parser = entry->parser_switch;
            return false;
        }
    }
    else {
        mycss_selectors_parser_expectations_error(entry, selectors, selector, token);
        entry->parser = entry->parser_switch;
        return false;
    }
    
    return true;
}

bool mycss_selectors_state_simple_selector_ident(mycss_entry_t* entry, mycss_selectors_t* selectors, mycss_selectors_entry_t* selector, mycss_token_t* token)
{
    if(token->type == MyCSS_TOKEN_TYPE_DELIM) {
        if(*token->data == '|') {
            // HAND_EDIT_BEGIN
            mycss_selectors_parser_selector_namespace_ident(entry, selectors, selector, token);
            // HAND_EDIT_END
            entry->parser_state = mycss_selectors_state_simple_selector_ident_vertical_bar;
            
            if(entry->parser != mycss_selectors_state_token_all)
                entry->parser = mycss_selectors_state_token_all;
        }
        else {
            mycss_selectors_parser_selector_end(entry, selectors, selector, token);
            entry->parser = entry->parser_switch;
            return false;
        }
    }
    else {
        mycss_selectors_parser_selector_end(entry, selectors, selector, token);
        entry->parser = entry->parser_switch;
        return false;
    }
    
    return true;
}

bool mycss_selectors_state_simple_selector_ident_vertical_bar(mycss_entry_t* entry, mycss_selectors_t* selectors, mycss_selectors_entry_t* selector, mycss_token_t* token)
{
    if(token->type == MyCSS_TOKEN_TYPE_IDENT) {
        mycss_selectors_parser_selector_after_namespace(entry, selectors, selector, token);
        mycss_selectors_parser_selector_end(entry, selectors, selector, token);
        MyCSS_DEBUG_MESSAGE("mycss_selectors_state_simple_selector_ident_vertical_bar_ident")
        entry->parser = entry->parser_switch;
    }
    else if(token->type == MyCSS_TOKEN_TYPE_DELIM) {
        if(*token->data == '*') {
            mycss_selectors_parser_selector_after_namespace(entry, selectors, selector, token);
            mycss_selectors_parser_selector_end(entry, selectors, selector, token);
            MyCSS_DEBUG_MESSAGE("mycss_selectors_state_simple_selector_ident_vertical_bar_asterisk")
            entry->parser = entry->parser_switch;
        }
        else {
            mycss_selectors_parser_expectations_error(entry, selectors, selector, token);
            entry->parser = entry->parser_switch;
            return false;
        }
    }
    else {
        mycss_selectors_parser_expectations_error(entry, selectors, selector, token);
        entry->parser = entry->parser_switch;
        return false;
    }
    
    return true;
}

bool mycss_selectors_state_shared_after_wq_name_attr(mycss_entry_t* entry, mycss_selectors_t* selectors, mycss_selectors_entry_t* selector, mycss_token_t* token)
{
    switch (token->type) {
        case MyCSS_TOKEN_TYPE_INCLUDE_MATCH: {
            if(selector->value == NULL)
                selector->value = mycss_selectors_value_attribute_create(entry, true);
            
            mycss_selector_value_attribute(selector->value)->match = MyCSS_SELECTORS_MATCH_INCLUDE;
            entry->parser_state = mycss_selectors_state_shared_after_attr_matcher;
            
            if(entry->parser != mycss_selectors_state_token_skip_whitespace)
                entry->parser = mycss_selectors_state_token_skip_whitespace;
            break;
        }
        case MyCSS_TOKEN_TYPE_DASH_MATCH: {
            if(selector->value == NULL)
                selector->value = mycss_selectors_value_attribute_create(entry, true);
            
            mycss_selector_value_attribute(selector->value)->match = MyCSS_SELECTORS_MATCH_DASH;
            entry->parser_state = mycss_selectors_state_shared_after_attr_matcher;
            
            if(entry->parser != mycss_selectors_state_token_skip_whitespace)
                entry->parser = mycss_selectors_state_token_skip_whitespace;
            break;
        }
        case MyCSS_TOKEN_TYPE_PREFIX_MATCH: {
            if(selector->value == NULL)
                selector->value = mycss_selectors_value_attribute_create(entry, true);
            
            mycss_selector_value_attribute(selector->value)->match = MyCSS_SELECTORS_MATCH_PREFIX;
            entry->parser_state = mycss_selectors_state_shared_after_attr_matcher;
            
            if(entry->parser != mycss_selectors_state_token_skip_whitespace)
                entry->parser = mycss_selectors_state_token_skip_whitespace;
            break;
        }
        case MyCSS_TOKEN_TYPE_SUFFIX_MATCH: {
            if(selector->value == NULL)
                selector->value = mycss_selectors_value_attribute_create(entry, true);
            
            mycss_selector_value_attribute(selector->value)->match = MyCSS_SELECTORS_MATCH_SUFFIX;
            entry->parser_state = mycss_selectors_state_shared_after_attr_matcher;
            
            if(entry->parser != mycss_selectors_state_token_skip_whitespace)
                entry->parser = mycss_selectors_state_token_skip_whitespace;
            break;
        }
        case MyCSS_TOKEN_TYPE_SUBSTRING_MATCH: {
            if(selector->value == NULL)
                selector->value = mycss_selectors_value_attribute_create(entry, true);
            
            mycss_selector_value_attribute(selector->value)->match = MyCSS_SELECTORS_MATCH_SUBSTRING;
            entry->parser_state = mycss_selectors_state_shared_after_attr_matcher;
            
            if(entry->parser != mycss_selectors_state_token_skip_whitespace)
                entry->parser = mycss_selectors_state_token_skip_whitespace;
            break;
        }
        case MyCSS_TOKEN_TYPE_DELIM: {
            if(*token->data == '=') {
                if(selector->value == NULL)
                    selector->value = mycss_selectors_value_attribute_create(entry, true);
                
                mycss_selector_value_attribute(selector->value)->match = MyCSS_SELECTORS_MATCH_EQUAL;
                entry->parser_state = mycss_selectors_state_shared_after_attr_matcher;
                
                if(entry->parser != mycss_selectors_state_token_skip_whitespace)
                    entry->parser = mycss_selectors_state_token_skip_whitespace;
            }
            else {
                mycss_selectors_parser_expectations_error(entry, selectors, selector, token);
                entry->parser = entry->parser_switch;
                return false;
            }
            break;
        }
        case MyCSS_TOKEN_TYPE_RIGHT_SQUARE_BRACKET: {
            mycss_selectors_parser_selector_end(entry, selectors, selector, token);
            MyCSS_DEBUG_MESSAGE("mycss_selectors_state_shared_after_wq_name_attr_right_bracket")
            entry->parser = entry->parser_switch;
            break;
        }
        default: {
            mycss_selectors_parser_expectations_error(entry, selectors, selector, token);
            entry->parser = entry->parser_switch;
            return false;
        }
    }
    
    return true;
}

bool mycss_selectors_state_shared_after_attr_modifier(mycss_entry_t* entry, mycss_selectors_t* selectors, mycss_selectors_entry_t* selector, mycss_token_t* token)
{
    if(token->type == MyCSS_TOKEN_TYPE_RIGHT_SQUARE_BRACKET) {
        mycss_selectors_parser_selector_end(entry, selectors, selector, token);
        MyCSS_DEBUG_MESSAGE("mycss_selectors_state_shared_after_attr_modifier_right_bracket")
        entry->parser = entry->parser_switch;
    }
    else {
        mycss_selectors_parser_expectations_error(entry, selectors, selector, token);
        entry->parser = entry->parser_switch;
        return false;
    }
    
    return true;
}

bool mycss_selectors_state_shared_after_attribute_value(mycss_entry_t* entry, mycss_selectors_t* selectors, mycss_selectors_entry_t* selector, mycss_token_t* token)
{
    if(token->type == MyCSS_TOKEN_TYPE_IDENT) {
        if(*token->data == 'i') {
            mycss_selectors_parser_selector_modifier(entry, selectors, selector, token);
            entry->parser_state = mycss_selectors_state_shared_after_attr_modifier;
            
            if(entry->parser != mycss_selectors_state_token_skip_whitespace)
                entry->parser = mycss_selectors_state_token_skip_whitespace;
        }
        else {
            mycss_selectors_parser_expectations_error(entry, selectors, selector, token);
            entry->parser = entry->parser_switch;
            return false;
        }
    }
    else if(token->type == MyCSS_TOKEN_TYPE_RIGHT_SQUARE_BRACKET) {
        mycss_selectors_parser_selector_end(entry, selectors, selector, token);
        MyCSS_DEBUG_MESSAGE("mycss_selectors_state_shared_after_attribute_value_right_bracket")
        entry->parser = entry->parser_switch;
    }
    else {
        mycss_selectors_parser_expectations_error(entry, selectors, selector, token);
        entry->parser = entry->parser_switch;
        return false;
    }
    
    return true;
}

bool mycss_selectors_state_shared_after_attr_matcher(mycss_entry_t* entry, mycss_selectors_t* selectors, mycss_selectors_entry_t* selector, mycss_token_t* token)
{
    if(token->type == MyCSS_TOKEN_TYPE_IDENT) {
        mycss_selectors_parser_selector_value(entry, selectors, selector, token);
        entry->parser_state = mycss_selectors_state_shared_after_attribute_value;
        
        if(entry->parser != mycss_selectors_state_token_skip_whitespace)
            entry->parser = mycss_selectors_state_token_skip_whitespace;
    }
    else if(token->type == MyCSS_TOKEN_TYPE_STRING) {
        mycss_selectors_parser_selector_value(entry, selectors, selector, token);
        entry->parser_state = mycss_selectors_state_shared_after_attribute_value;
        
        if(entry->parser != mycss_selectors_state_token_skip_whitespace)
            entry->parser = mycss_selectors_state_token_skip_whitespace;
    }
    else {
        mycss_selectors_parser_expectations_error(entry, selectors, selector, token);
        entry->parser = entry->parser_switch;
        return false;
    }
    
    return true;
}

